#!/usr/bin/python
#tb.py

import traceback
import os
import time
from function import *
from user_tunnel_info import *
from tunnel_local_manage import *
from ping_test import*


def main():
    login_flag = read_config('State','if_login')
    if login_flag==0:
        return 0
    write_tunnel_A()
    create_tunnel_A()
    print"cA"
    time.sleep(3)
    error = ping_test()
    if error == 1:
        write_state('if_first_login','1')
        return 1
    print"dA"
    delete_tunnel_A()
    write_tunnel_C()
    create_tunnel_C()
    print"cC"
    time.sleep(10)
    error = ping_test()
    if error == 1:
        write_state('if_first_login','1')
        return 2
    print"dC"
    delete_tunnel_C()
    write_state('if_first_login','1')
    return -1

if __name__=='__main__':
    try:
         main()
    except Exception,e:
         print str(e)
         traceback.print_exc()
         os._exit(1)
