#!/usr/bin/python
#tb.py

import traceback
import os
import time
from function import *
from user_tunnel_info import *
from tunnel_local_manage import *
from ping_test import*


def main():
    flag_2=0
    flag_1=0
    flag_22=0
    login_flag = read_config('State','if_login')
    if login_flag==0:
        mac = get_mac()
        error = write_userinfo(mac)
        if error == 1:
            os.system('/home/wtw/Djcode/mysite/script/network_config.shell')
            write_tunnel_C()
            create_tunnel_C()
        return 0
    
    time.sleep(5)        
    error=ping_test()
    #print error
    if error==0:
        while flag_2<2:
            os.system("sudo service openvpn restart")
            time.sleep(10)
            error_2 = ping_test()
            if error_2!=0:
                break
            flag_2+=1
        if error_2 == 0:
            delete_tunnel_C()
            write_tunnel_C()
            create_tunnel_C()            
    return 1
                

if __name__=='__main__':
     try:
          main()
     except Exception,e:
          print str(e)
          traceback.print_exc()
          os._exit(1)

