# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_data', '0002_net_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='net_data',
            name='record_date',
        ),
        migrations.AlterField(
            model_name='net_data',
            name='record_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
