# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_data', '0005_auto_20160427_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_term_sample_period', models.IntegerField()),
                ('long_term_volumn', models.IntegerField()),
                ('short_term_sample_period', models.IntegerField()),
                ('short_term_volumn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CPU_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_unniced_user', models.FloatField()),
                ('cpu_kernel', models.FloatField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='long_term_dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set', models.ManyToManyField(to='net_data.CPU_data')),
            ],
        ),
        migrations.CreateModel(
            name='short_term_dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set', models.ManyToManyField(to='net_data.CPU_data')),
            ],
        ),
        migrations.RemoveField(
            model_name='client_info',
            name='ipv6_addresses',
        ),
        migrations.DeleteModel(
            name='net_data',
        ),
        migrations.DeleteModel(
            name='client_info',
        ),
        migrations.DeleteModel(
            name='ipv6_address',
        ),
    ]
