# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_data', '0006_auto_20160430_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_info',
            name='ivi_address',
            field=models.CharField(default='test_global_address', max_length=20),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='global_ipv6_address',
            field=models.CharField(default='No IPv6 Address', max_length=20),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='mac_address',
            field=models.CharField(default='No Mac Address', max_length=20),
        ),
        migrations.AlterField(
            model_name='wlan_configuration',
            name='password',
            field=models.CharField(default='1234567890', max_length=60),
        ),
    ]
