# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_data', '0007_auto_20160511_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='ivi_address_pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
