# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_data', '0008_ivi_address_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='ivi_address_pool',
            name='mac',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='ivi_address_pool',
            name='pid',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='global_ipv6_address',
            field=models.CharField(default='No IPv6 Address', max_length=100),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='ivi_address',
            field=models.CharField(default='test_global_address', max_length=100),
        ),
        migrations.AlterField(
            model_name='ipv6_address',
            name='ipv6_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ivi_address_pool',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
