# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_data', '0010_ivi_address_pool_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_info',
            name='life',
            field=models.CharField(default='active', max_length=100),
        ),
        migrations.AddField(
            model_name='client_info',
            name='position',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='client_info',
            name='prefix',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
