# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_data', '0011_auto_20160515_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_info',
            name='global_ipv6_address',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='ivi_address',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='life',
            field=models.CharField(default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='mac_address',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
