# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('net_data', '0003_auto_20160426_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=20)),
                ('global_ipv6_address', models.CharField(max_length=20)),
                ('last_active_time', models.DateTimeField(auto_now=True)),
                ('service_start_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ipv6_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv6_address', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.AddField(
            model_name='client_info',
            name='ipv6_addresses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='net_data.ipv6_address'),
        ),
    ]
