# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_data', '0004_auto_20160427_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_info',
            name='ipv6_addresses',
        ),
        migrations.AddField(
            model_name='client_info',
            name='ipv6_addresses',
            field=models.ManyToManyField(to='net_data.ipv6_address'),
        ),
    ]
