# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_data', '0005_auto_20160427_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='wlan_configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.IntegerField(default=6)),
                ('password', models.CharField(max_length=60)),
                ('dying_time', models.IntegerField(default=30)),
                ('refreshing_client_time', models.IntegerField(default=5)),
            ],
        ),
        migrations.DeleteModel(
            name='net_data',
        ),
        migrations.AddField(
            model_name='client_info',
            name='heart_beat_frequency',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='service_start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
