# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 07:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('net_data', '0009_auto_20160512_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='ivi_address_pool',
            name='time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 12, 7, 5, 22, 392731, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
