# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_data', '0010_ivi_address_pool_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='prefix_address_pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('global_address', models.CharField(default='None', max_length=100)),
                ('pid', models.CharField(default='None', max_length=100)),
                ('mac', models.CharField(default='None', max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
