#!/usr/bin/python
#tb.py

import traceback
import os
import time
from function import *
from user_tunnel_info import *
from tunnel_local_manage import *
from ping_test import*

def main():
    login_flag = read_config('State','if_login')
    mac = get_mac()
    if login_flag==0:
        error = write_userinfo(mac)
        if error == 1:
            os.system('/project/Djcode/mysite/script/network_config.shell')
    else:
        v4glb = tunnel_communicate_mac(mac,'v4glb')
        write_v4glb(v4glb)
        os.system('sudo service radvd start')
#       os.system('sudo service apache2 start')
    tunnel_type = 2
    if tunnel_type == 2:
        write_tunnel_C()
        create_tunnel_C()
    return 1


if __name__=='__main__':
    try:
         main()
    except Exception,e:
         print str(e)
         traceback.print_exc()
         os._exit(1)
