#!/usr/bin/python
#tb.py

import traceback
import os
import time
from function import *
from user_tunnel_info import *
from tunnel_local_manage import *

RX_cmd="cat /proc/net/dev | grep tap0 | tr : ' ' | awk '{print $2}' "
TX_cmd="cat /proc/net/dev | grep tap0 | tr : ' ' | awk '{print $10}' "
FLOW_FILE="/etc/tunnel_config/flow.tmp"


def pping_test():
    t_cmd = "sudo ping6 -c 3 ipv6.google.com"
    flag=0
    i=-1
    while(i<3):
        i+=1 
        login_flag=read_config('State','if_login')
        if login_flag==0:
            continue
        ipv6_addr = read_config('TunnelInfo','ipv6_addr')
        cmd = t_cmd+" -I "+ipv6_addr
        print cmd
        t_out = send_message(cmd)
        print t_out
        out = t_out.split('\n')
        nn = out[0]
        if len(nn)>=3:
            n4 = out[6]
            out1 = n4.split(',')
            if(len(out1)<2):
                continue
            out2 = out1[1]
            out3 = out2[1]
            t = len(out[1])
            if out3 != '0':
                rtt=out[7].split('/')
                rtt_avg = rtt[4]
                print 1
                return (1,rtt_avg)
    print 0
    return (0,'-1')

def main():
    flag_2=0
    flow_info = read_file(FLOW_FILE).split('\n')
    relay=0
    RX_recent=float(flow_info[0])
    TX_recent=float(flow_info[1])
    packet_loss=0
    bandwidth=0
    first_error = read_config('State','if_first_login')
    if first_error=='0':
        return 0
    tunnel_type = read_config('State','tunnel_type')
    if tunnel_type == '0':
        return 0
    error_tuple=pping_test()
    if error_tuple[0]==1:
        RX_now = float(send_message(RX_cmd).split('\n')[0])/1024
        TX_now = float(send_message(TX_cmd).split('\n')[0])/1024
        print "RX:"+str(RX_now)
        in_t = RX_now-RX_recent
        out_t = TX_now-TX_recent
        in_flow = float('%.10f'% in_t)
        out_flow = float('%.10f'% out_t)
        if in_flow <=0 or out_flow<=0:
            in_flow = float(flow_info[2])
            out_flow = float(flow_info[3])
        relay=float(error_tuple[1])
        ip4_local = get_ip('eth0')
        re=tunnel_communicate_name_state(tunnel_type,relay,in_flow,out_flow,ip4_local) 
        strimg = str(RX_now)+'\n'+str(TX_now)+'\n'+str(in_flow)+'\n'+str(out_flow)+'\n'
        write_file(FLOW_FILE,strimg)
        print re
        

       

if __name__=='__main__':
     try:
          main()
     except Exception,e:
          print str(e)
          traceback.print_exc()
          os._exit(1)

