#!/usr/bin/python
#chang_file.py

import traceback
import os

file_path = '/project/Djcode/mysite/networf_config/'
radvd_file = '/etc/radvd.conf'
interface_file = '/etc/network/interfaces'
openvpn_file = '/etc/openvpn/myhost.up'
iface1='iface eth0 inet6 static\naddress '
openvpn='/sbin/ifconfig $dev add '
def write_file(filename_input,filename_output,line_content,line_num):
    fp=file(filename_input)
    lines=[]
    for line in fp:
        lines.append(line)
    fp.close()
    
    lines.insert(line_num,line_content+'\n')
    s=''.join(lines)
    fp = file(filename_output,'w')
    fp.write(s)
    fp.close

def read_user_info():
    t_input=open('/etc/tunnel_config/user_info','r')
    all_text = t_input.read()
    t_input.close()
    t_file = all_text.split(',')
    return t_file

def read_tunnel_info():
    t_input=open('/etc/tunnel_config/tunnel_info','r')
    all_text = t_input.read()
    t_input.close()
    t_flag = t_input.split(',')[0]
    return int(t_flag)

def main():
    tunnel_info = read_tunnel_info()
    user_info = read_user_info()
    write_file(file_path+'radvd.conf',radvd_file,'\tprefix '+user_info[3]+'/64',6)
    if tunnel_info[0]=='1':
        t1 = iface1+tunnel_info[3]+'\n'+'netmask 64\n\n'
        ivi_address = tunnel_info[5].split('/')
        t2 = iface1+ivi_address[0]+'\n'+'netmask '+ivi_address[1]+'\n'
        t_iface = t1+t2
        write_file(file_path+'interfaces',interface_file,t_iface,19)
       
        t_openvpn = openvpn+tunnel_info[4]+'/64'
        write_file(file_path+'myhost.up',openvpn_file,t_openvpn,4)       
        

if __name__=='__main__':
    try:
        main()
    except Exception,e:
        print str(e)
        traceback.print_exc()
        os._exit(1)    
